# config/config.yaml

# Data configuration
data:
  raw_path: "C:\\Users\\28151\\Desktop\\Updated code files\\dataset"
  test_size: 0.2
  chunk_size: 500  # For memory-safe chunk processing
  downsample_factor: 1  # Set to 2+ to reduce data volume

# Preprocessing configuration
preprocessing:
  variance_threshold: 1e-4  # More aggressive feature filtering
  max_features: 50  # Limit total features after processing
  apply_detrend: false  # Disable memory-heavy detrending
  normalize_energy: true

# PEECOM fault injection configuration
peecom:
  fault_types: ["pressure_spike", "flow_drop", "temp_drift"]
  fault_probability: 0.3
  min_fault_duration: 1
  max_fault_duration: 5
  energy_metrics: ["EPS1", "CP"]
  max_sensor_cols: 1000  # Truncate long sensor recordings

# Sensor configuration (optimized for memory)
sensors:
  # Dynamic sensor loading - sensors found in data will be used
  - name: TS*  # Matches TS1-TS4
    hz: 1
    cols: 60
    keep_cols: 20  # Percentage of columns to use
  - name: VS*  # Matches VS1
    hz: 1
    cols: 60
    keep_cols: 20
  - name: CE
    hz: 1
    cols: 60
    keep_cols: 20
  - name: CP
    hz: 1
    cols: 60
    keep_cols: 100  # Critical sensor - keep all
  - name: SE
    hz: 1
    cols: 60
    keep_cols: 20
  - name: FS*  # Matches FS1-FS2
    hz: 10
    cols: 600
    keep_cols: 10
  - name: PS*  # Matches all pressure sensors
    hz: 100
    cols: 6000
    keep_cols: 5
  - name: EPS*
    hz: 100
    cols: 6000
    keep_cols: 10  # Energy sensor - keep more columns

# Model configuration (memory-optimized)
model:
  input_timesteps: 10
  batch_size: 8        # Lowered for 8GB RAM
  conv_filters: 16     # Lowered for CPU/memory
  lstm_units: 64       # Lowered for CPU/memory
  attn_units: 32       # Lowered for CPU/memory
  input_features: auto  # Will automatically use available features
  epochs: 50
  learning_rate: 0.001
  save_path: "output/trained_model.keras"
  fp16_precision: false  # Disable mixed precision for Vega 8

# Hyperparameter tuning configuration
tuning:
  max_trials: 10
  executions_per_trial: 1  # Reduced for memory
  directory: "tuner_logs"
  project_name: "PEECOM_tuning"
  hyperband_iterations: 1  # Memory optimization

# Physics configuration
physics:
  alpha: 0.3
  sensor_adjacency: null
  adj_threshold: 0.5  # For sparse adjacency matrix
  feature_limit: 20   # Max features used in physics layer

# Memory management configuration
memory:
  max_gpu_mb: 4096    # Limit GPU memory usage
  cpu_buffer_mb: 1024  # Reserve CPU memory
  garbage_collect_interval: 1000  # Batch intervals
  max_sequence_length: 20    # Reduced maximum sequence length
  max_features: 500          # Reduced feature count

# Logging configuration
logging:
  dir: "logs"
  interval: 100       # Steps between logging
  profile_batch: 0    # Disable memory-heavy profiling
  checkpoint_format: "weights_only"  # options: full_model/weights_only

# Execution configuration
execution:
  cpu_features:
    avx512: true
    mkl_threads: 4
    numa_aware_data: true
  tf2_19_flags:
    experimental_memory_optimization: true
    optimize_dataset_ops: true
  force_cpu: false
  memory_safety: true
  mixed_precision: false  # Disable for Vega 8
  xla_compilation: true  # Enable TensorFlow XLA optimization

# Add new dynamic feature section
feature_selection:
  enabled: true
  exclude_sensors: []  # Empty list = exclude nothing, can be populated at runtime
  auto_remove_bad_sensors: true  # Will remove sensors with critical health scores