data:
  data_dir: "./dataset"
  processed_dir: "./processed_data"
  common_settings:
    resize: [224, 224] # Standard size for all datasets
    channels: 3 # Enforce RGB
    pad_to_square: true
    normalize: true
    normalization:
      mean: [0.485, 0.456, 0.406] # ImageNet stats as default
      std: [0.229, 0.224, 0.225]
    quality_filtering:
      enabled: true
      min_std_dev: 10
      min_brightness: 15
      max_brightness: 240
    color_standardization:
      force_rgb: true

  dataset_structure:
    standard: # datasets with train/val/test
      - chest_xray
      - roct
    train_test: # datasets with only train/test
      - dermnet
      - scisic
      - cattled
    train_valid_test: # datasets with train/valid/test
      - ccts
    class_based: # datasets with class folders
      - tbcr
      - seabed
    metadata_format:
      tbcr:
        - "Normal.metadata.xlsx"
        - "Tuberculosis.metadata.xlsx"

  data_key:
    - name: scisic
      modality: dermoscopy
      train_dir: "scisic/Train"
      test_dir: "scisic/Test"
      normalization:
        mean: [0.7437659, 0.58653116, 0.58686644]
        std: [0.08040085, 0.10757149, 0.12017569]
      augmentation:
        contrast_enhancement: true
        brightness_adjustment: true  # Enable brightness adjustment
        contrast_factor: 1.5  # Reduced from 2.0 which was too aggressive
        brightness_factor: 1.2  # Moderate brightness increase
        random_rotation: true  # Add rotation augmentation
        random_horizontal_flip: true
        advanced: true  # Enable advanced augmentations
      class_balancing: weighted_sampler  # use sampler in dataloader
      preprocessing:
        clahe: true
        aspect_preserve_resize: true
        color_correction:
          white_balance: true
          saturation_factor: 1.1  # Reduced from 1.2
          temperature: -0.1  # Slightly cooler temperature
        quality_filtering:
          enabled: true
          min_std_dev: 10  # Increased from 8
          min_brightness: 20  # Add minimum brightness threshold
      duplicate_removal: true
      structure:
        type: "train_test"
        train: "Train"
        test: "Test"
        split_ratios: [0.8, 0.2]  # More standard split ratio
      training:
        epochs: 30  # Increased from 5
        batch_size: 24  # Reduced from 32
        lr: 0.0005  # Reduced learning rate
        momentum: 0.9
        weight_decay: 2e-4  # Increased regularization
        early_stopping: true  # Add early stopping
      padding:
        enabled: true
        strategy: "symmetric"

    - name: ccts
      modality: ct
      train_dir: "ccts/train"
      test_dir: "ccts/test"
      normalization:
        mean: [0.323004, 0.32297248, 0.32300267]
        std: [0.22162104, 0.22161943, 0.2216194]
      conversion: convert_to_3_channel # Important - handles multiple channel types
      duplicate_removal: true
      preprocessing:
        hu_window: [-1000, 400]
        aspect_preserve_resize: true
        color_standardization:
          force_rgb: true
        quality_filtering:
          enabled: true
      structure:
        train: "train"
        valid: "valid"
        test: "test"
        type: "train_valid_test"
      class_normalization:
        # Define rules for normalizing class names
        patterns:
          # Pattern-based replacement (regex)
          "^(adenocarcinoma).*": "adenocarcinoma"
          "^(large\\.cell\\.carcinoma).*": "large.cell.carcinoma"
          "^(squamous\\.cell\\.carcinoma).*": "squamous.cell.carcinoma"
        # Optional direct mappings for specific cases
        mapping:
          "adenocarcinoma_left.lower.lobe_T2_N0_M0_Ib": "adenocarcinoma"
          "large.cell.carcinoma_left.hilum_T2_N2_M0_IIIa": "large.cell.carcinoma"
          "squamous.cell.carcinoma_left.hilum_T1_N2_M0_IIIa": "squamous.cell.carcinoma"
      training:
        epochs: 30
        batch_size: 64
        lr: 0.0001
        momentum: 0.9
        weight_decay: 1e-4
      augmentation:
        contrast_enhancement: false # Contrast levels are acceptable
      padding:
        enabled: true
        strategy: "symmetric"

    - name: roct
      modality: oct
      train_dir: "roct/train"
      test_dir: "roct/test"
      normalization:
        mean: [0.19338988, 0.19338988, 0.19338988]
        std: [0.1933612, 0.1933612, 0.1933612]
      conversion: convert_to_3_channel # Change to handle grayscale images
      duplicate_removal: true
      structure:
        train: "train"
        val: "val"
        test: "test"
      training:
        epochs: 100
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      augmentation:
        brightness_adjustment: true # Added due to low brightness
        brightness_factor: 2.0  # Significantly increase brightness 
      preprocessing:
        clahe: true # For contrast enhancement
        aspect_preserve_resize: true # Handle varying aspect ratios
        image_enhancement:
          brightness_factor: 1.8  # Address low brightness (49.33)
          auto_equalize: true     # Enhance overall image quality
      padding:
        enabled: true
        mode: "constant"
        value: 0

    - name: kvasir
      modality: endoscopy
      train_dir: "kvasir/train"
      normalization:
        mean: [0.48510954, 0.34737176, 0.30044696]
        std: [0.29461348, 0.22394758, 0.19942161]
      duplicate_removal: true
      structure:
        train: "train"
      preprocessing:
        aspect_preserve_resize: true
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      padding:
        enabled: true
        strategy: "symmetric" # For handling varying dimensions
      augmentation:
        contrast_enhancement: false # Contrast is acceptable

    - name: dermnet
      modality: dermoscopy
      train_dir: "dermnet/train"
      test_dir: "dermnet/test"
      normalization:
        mean: [0.5414171, 0.41425624, 0.382362]
        std: [0.18633145, 0.15891077, 0.15291688]
      augmentation:  # Add comprehensive augmentation
        contrast_enhancement: true
        brightness_adjustment: true
        contrast_factor: 1.3
        brightness_factor: 1.1
        random_rotation: true
        random_horizontal_flip: true
        advanced: true
      duplicate_removal: true
      preprocessing:
        clahe: true
        aspect_preserve_resize: true
        color_correction:  # Add color correction
          white_balance: true
          saturation_factor: 1.1
        image_enhancement:  # Add image enhancement
          auto_equalize: true
        quality_filtering:
          enabled: true
          min_std_dev: 12
          min_brightness: 20
      class_balancing: "weighted_loss_focal"  # Switch to focal loss for better handling of imbalance
      structure:
        type: "train_test"
        train: "train"
        test: "test"
        split_ratios: [0.8, 0.2]  # More standard split
      training:
        epochs: 40  # Increased from 30
        batch_size: 32  # Keep batch size
        lr: 0.0003  # Lower learning rate
        lr_scheduler: "cosine"  # Add LR scheduler
        momentum: 0.9
        weight_decay: 3e-4

    - name: chest_xray
      modality: xray
      train_dir: "chest_xray/train"
      test_dir: "chest_xray/test"
      normalization:
        mean: [0.48230693, 0.48230693, 0.48230693]
        std: [0.22157896, 0.22157896, 0.22157896]
      conversion: convert_to_3_channel # Handle both grayscale and RGB
      duplicate_removal: true
      structure:
        train: "train"
        val: "val"
        test: "test"
      preprocessing:
        remove_noise: true
        aspect_preserve_resize: true
        color_standardization:
          force_rgb: true
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      padding:
        enabled: true
        strategy: "symmetric" # For varying dimensions
      preprocessing:
        remove_noise: true # Add noise reduction

    - name: tbcr
      modality: ct
      train_dir: "tbcr"
      normalization:
        mean: [0.5013298, 0.5097307, 0.5125384]
        std: [0.23488876, 0.23702013, 0.2381724]
      conversion: convert_to_3_channel
      duplicate_removal: true
      augmentation:  # Add augmentation for better balance
        random_rotation: true
        random_horizontal_flip: true
        contrast_enhancement: true
        contrast_factor: 1.2
      class_balancing: "weighted_sampler"  # Change from default to explicit weighted sampler
      preprocessing:
        color_standardization:
          force_rgb: true
        quality_filtering:
          enabled: true
          min_std_dev: 10
      structure:
        type: "class_based"
        classes:
          - "Normal"
          - "Tuberculosis"
        metadata_files:
          - "Normal.metadata.xlsx"
          - "Tuberculosis.metadata.xlsx"
        split_ratios: [0.7, 0.15, 0.15]
        minority_oversampling: true  # Add oversampling for minority class
      training:
        epochs: 30
        batch_size: 48  # Reduced from 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
        mixup_alpha: 0.2  # Add mixup for improved robustness

    - name: miccai_brats2020
      modality: mri
      train_dir: "miccai_brats2020/MICCAI_BraTS2020_TrainingData"
      normalization:
        mean: [0.5, 0.5, 0.5]
        std: [0.25, 0.25, 0.25]
      conversion: none
      duplicate_removal: true
      structure:
        train: "MICCAI_BraTS2020_TrainingData"
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
        
    - name: cattled
      modality: camera
      train_dir: "cattled"
      normalization:
        mean: [0.51026833, 0.47605217, 0.41803247]
        std: [0.23365363, 0.23278123, 0.23798749]
      conversion: convert_to_3_channel
      duplicate_removal: true
      preprocessing:
        aspect_preserve_resize: true
        color_standardization:
          force_rgb: true
        quality_filtering:
          enabled: true
      structure:
        type: "train_test"
        train: "Training"
        test: "Testing"
        split_ratios: [0.7, 0.15, 0.15]
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      padding:
        enabled: true
        strategy: "symmetric"

    - name: seabed
      modality: underwater
      train_dir: "seabed"
      normalization:
        mean: [0.23699918, 0.22173119, 0.2078459]
        std: [0.12826255, 0.1245552, 0.11818483]
      conversion: convert_to_3_channel # Handle mix of grayscale and RGB
      duplicate_removal: true
      augmentation:
        contrast_enhancement: true
        brightness_adjustment: true
        contrast_factor: 1.3
        brightness_factor: 1.5  # Increase brightness as analysis showed average of 57.29
        random_rotation: true
        random_horizontal_flip: true
        advanced: true
      class_balancing: "weighted_sampler"  # Address severe class imbalance (ratio: 39.24)
      preprocessing:
        aspect_preserve_resize: true  # Important for varying dimensions (1319 unique sizes)
        color_standardization:
          force_rgb: true  # Standardize mixed color spaces ('L' and 'RGB')
        quality_filtering:
          enabled: true
          min_std_dev: 10
          min_brightness: 15  # Preserve lower brightness images
      structure:
        type: "class_based"
        split_ratios: [0.7, 0.15, 0.15]
        minority_oversampling: true  # Additional help for severe class imbalance
      training:
        epochs: 50  # More epochs for imbalanced dataset
        batch_size: 32
        lr: 0.0003  # Lower learning rate for better convergence
        momentum: 0.9
        weight_decay: 2e-4
        mixup_alpha: 0.2  # Add mixup for imbalanced classes
      padding:
        enabled: true
        strategy: "symmetric"  # For varying aspect ratios (0.26-4.05)
